name:                siminitt
version:             0.1.0.0
github:              "WANG-QUFEI/thesis"
license:             BSD3
author:              "qufei"
maintainer:          "wangqufei2009@gmail.com"
copyright:           "Copyright (c) 2020 Qufei Wang"
synopsis:            A simplified version of Mini-TT
category:            "Type theory, dependent types"
description:         Please see the README on GitHub at <https://github.com/WANG-QUFEI/thesis#readme>

ghc-options: -Wall

extra-source-files:
- README.md
- extra-sources/*

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2
- containers >= 0.6.2
- array >= 0.5.4
- directory >= 1.3.6.0
- haskeline >= 0.8.1.0
- split ^>= 0.2.3.4
- text >= 1.2.4.0
- unicode-show >= 0.1.0.4

executables:
  siminitt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -main-is Spec
