-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module Core.Abs where

import Prelude (Char, Double, Int, Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)

newtype Id = Id ((Int, Int), String)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Program = Prog [Exp]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
    = EU
    | EVar Id
    | EApp Exp Exp
    | EArr Exp Exp
    | EPi Id Exp Exp
    | EPost Id Exp
    | EDec Id Def
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Def = Def Exp Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

