-- Haskell module generated by the BNF converter

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Core.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Core.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transId :: Core.Abs.Id -> Result
transId x = case x of
  Core.Abs.Id string -> failure x

transContext :: Core.Abs.Context -> Result
transContext x = case x of
  Core.Abs.Ctx cdecls -> failure x

transCExp :: Core.Abs.CExp -> Result
transCExp x = case x of
  Core.Abs.CU -> failure x
  Core.Abs.CVar id -> failure x
  Core.Abs.CApp cexp1 cexp2 -> failure x
  Core.Abs.CArr cexp1 cexp2 -> failure x
  Core.Abs.CPi id cexp1 cexp2 -> failure x
  Core.Abs.CWhere id cexp1 cexp2 cexp3 -> failure x

transCDecl :: Core.Abs.CDecl -> Result
transCDecl x = case x of
  Core.Abs.CDec id cexp -> failure x
  Core.Abs.CDef id cexp1 cexp2 -> failure x
